ALTER TABLE tenant_branding
    ADD COLUMN IF NOT EXISTS show_boards BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS show_feed BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE boards
    ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN NOT NULL DEFAULT TRUE;
